### ISSUE TITLE
model running

### ISSUE THREAD

**Issue by sunrise93** [basicai/xtreme1#28]
model running not working

**Comment by ToMaToJ** [comment]
Same issue here,

My environment：
System: Windows 10
Docker： v20.10.17
GPU：NVIDIA GeForce gtx 1060
GPU Driver：latest version

I do have Nvidia Driver here, and I still face error when i use  

`docker compose --profile model up`

![image](https://user-images.githubusercontent.com/10492049/191401509-ccecabf8-9f0a-4724-98d7-5fd45cba131a.png)
