### ISSUE TITLE
Unable to access app on remote server 

### ISSUE THREAD

**Issue by ToMaToJ** [basicai/xtreme1#31]
I have deployed Xtreme1 app on a remote server, but when I accessed it by my own pc, it pops up an error.
It looks like calling a wrong host 

![image](https://user-images.githubusercontent.com/10492049/191429874-b4772e9a-3b7a-4973-974c-52497b6b328e.png)

Please fix this bug

**Comment by jaggerwang** [comment]
Right now xtreme1 can only be accessed from localhost, but we are planning to fix this.
