### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by sunrise93** [basicai/xtreme1#32]
I'm trying to upload kitti dataset, but it show error. I suspect it is the camera parameter problem, please help. Thanks
[5frames.zip](https://github.com/basicai/xtreme1/files/9623242/5frames.zip)

**Comment by sccassiel** [comment]
Please provide more detailed error log. 
Thanks

**Comment by sccassiel** [comment]
> I'm trying to upload kitti dataset, but it show error. I suspect it is the camera parameter problem, please help. Thanks [5frames.zip](https://github.com/basicai/xtreme1/files/9623242/5frames.zip)

Please provide more detailed error log.
Thanks.

**Comment by nicozhan** [comment]
Solved after joining the Slack channel.

**Comment by nicozhan** [comment]
Solved after joining the Slack channel.
