### ISSUE TITLE
Not able to upload jpg images

### ISSUE THREAD

**Issue by sunrise93** [basicai/xtreme1#33]
Is jpg format not supported?
![WechatIMG4862](https://user-images.githubusercontent.com/113983400/191690281-e2d9ff59-8029-4e03-88af-46ad6148a7cd.jpeg)

**Comment by jaggerwang** [comment]
Can u supply your jpg image? It's ok on my local computer.

**Comment by nicozhan** [comment]
This issue was fixed in v0.5.1
