### ISSUE TITLE
can't annotate my data due to resource uploading issue

### ISSUE THREAD

**Issue by sunrise93** [basicai/xtreme1#34]
Hi,I met with resource loading issue while uploading data.
1. I uploaded LiDAR fusion type 
2. when I click annotate in data card I got an error information like this 
![IMG_2419](https://user-images.githubusercontent.com/113983400/191704755-35054da4-8e36-41bf-8bd1-5e3016583513.PNG)
3. the error information is as below
![IMG_2433](https://user-images.githubusercontent.com/113983400/191704799-ca57ef00-f9d0-454e-a0bf-a11a03a876d2.PNG)
Can anyone help me with this?

**Comment by jaggerwang** [comment]
Can you try the lastest version v0.5.1?

**Comment by sunrise93** [comment]
> Can you try the lastest version v0.5.1?

Ok. It works on the lastest version. Thanks.
