### ISSUE TITLE
Import data

### ISSUE THREAD

**Issue by ida88cd** [basicai/xtreme1#35]
I want to load the 3d data and their pre-annotation result (kitti dataset) while launching the xtreme1. 
We want to know whether it supports? Or is there any converter available to convert it?

**Comment by nicozhan** [comment]
Hi @ida88cd 
Yes. It is supported! Please follow the instruction -> [help doc](https://docs.basic.ai/docs/upload).

**Comment by Devoe-97** [comment]
> Hi @ida88cd Yes. It is supported! Please follow the instruction -> [help doc](https://docs.basic.ai/docs/upload).

This URL is not available. And, I would like to ask how to convert 3D detection annotations from xtreme1 to KITTI format
