### ISSUE TITLE
Network error when trial annotation and data uploading

### ISSUE THREAD

**Issue by Deephome** [basicai/xtreme1#39]
Hi, `network error` occurs when I try to annotate the provided lidar fusin data and upload the lidar sample dataset.

**Comment by nicozhan** [comment]
Hi there,
Thanks for using xtreme1!
I suppose you're using the software installing via Docker compose. Is that correct?
Could you provide the specific error log and screenshots?

If it's hard to describe, welcome to join our [Slack channel](https://join.slack.com/share/enQtNDE0MTk1MjEwMzEwNS1lM2Q0NThlOTIyOGZiM2EwY2YxYWVhNDgxYjU5NjkwOWU2Mjc4NDllNGNhMzZlYjdlOWEyZDkzNDBhMTJlZThm) to share more details.

**Comment by Deephome** [comment]
> Hi there, Thanks for using xtreme1! I suppose you're using the software installing via Docker compose. Is that correct? Could you provide the specific error log and screenshots?
> 
> If it's hard to describe, welcome to join our [Slack channel](https://join.slack.com/share/enQtNDE0MTk1MjEwMzEwNS1lM2Q0NThlOTIyOGZiM2EwY2YxYWVhNDgxYjU5NjkwOWU2Mjc4NDllNGNhMzZlYjdlOWEyZDkzNDBhMTJlZThm) to share more details.

Yes, I use the software via Docker compose. When I try to annotate the lidar fusion trial dataset or upload new dataset, the webpage gives a hint "Network Error".

**Comment by jaggerwang** [comment]
Can you try the lastest version (v0.5.1), if you still have problems, please supply some screenshots, especially the network panel of Chrome Developer Panel.

**Comment by jaggerwang** [comment]
The reason may be that the backend service is not ready when nginx proxy requests to it, you can wait a few minutes to access. We have already fix this issue in main branch, and it will be released in next version (v0.5.2).
