### ISSUE TITLE
How to deploy own custom dataset and pre-trained model? 

### ISSUE THREAD

**Issue by TmacTmac1992** [basicai/xtreme1#42]
Hi, Thanks for open-source the code!  Do you have any doc or tutorial for deploying own custom dataset and pre-trained model?

**Comment by nicozhan** [comment]
Hi @TmacTmac1992 
(1) Deploying own custom dataset: 
Please find this [help doc](https://docs.basic.ai/docs/upload) for your reference.

(2) Deploying pre-trained model
You can load dataset with pre-labeling json on the platform directly. Does this meet your needs?
Also are you looking for connecting with your model?
May I ask which pre-trained model are you deploying?

**Comment by TmacTmac1992** [comment]
Thanks for your quick reply! 
Does xtreme1 support all model trained form Openpcdet?

**Comment by liu4lin** [comment]
Thanks for your interest. More models from openmmlab will be supported soon. Although the models from openmmlab share similar framework, the code has to be adapted to the Xtreme1. We also welcome more developers participating this project to optimize the interface and integrate more models.

**Comment by TmacTmac1992** [comment]
Thanks for your answer! 
Do you provide industry solution for xtreme1?

**Comment by nicozhan** [comment]
Yes, we do. Let’s discuss it more and please email to [may@basic.ai](may@basic.ai)
