### ISSUE TITLE
how to replace localhost to ip?

### ISSUE THREAD

**Issue by DIOYF** [basicai/xtreme1#44]
"you can open address http://localhost:8190 in your favorite browser (Chrome recommend) to try out Xtreme1. You can replace localhost to ip address if you want to access from another computer"
I deployed my docker and defining TCP/IP transition of localhost:8190 , but can not open from another computer.

**Comment by jaggerwang** [comment]
You can replace localhost to ip address of your computer if you want to access from another computer, you should use the latest v0.5.1.
