### ISSUE TITLE
融合标注 上传一组图片和点云 会生出2个重复的标注任务

### ISSUE THREAD

**Issue by heyu3913** [basicai/xtreme1#51]
<img width="774" alt="image" src="https://user-images.githubusercontent.com/72067297/197096649-9dd6994c-f530-42f8-9d11-e89c55d742b1.png">
<img width="990" alt="image" src="https://user-images.githubusercontent.com/72067297/197096902-b7ef1d1f-f56c-49c7-a4dd-f58eb344144e.png">

**Comment by nicozhan** [comment]
请问刷新后，是否还存在这个情况呢？
（也欢迎在交流群里反馈，我拉你进去，Tel/vx13051105869）

**Comment by jaggerwang** [comment]
请提供一下上传的压缩包，看看是否是压缩包格式不正确引起。

**Comment by heyu3913** [comment]
[lidar_fusion.zip](https://github.com/basicai/xtreme1/files/9835761/lidar_fusion.zip)

https://user-images.githubusercontent.com/72067297/197113988-b95bf7e5-eaeb-42e8-91c7-d3fd190929c6.mp4

上传步骤 与 压缩包已提供

**Comment by heyu3913** [comment]
[lidar_fusion.zip](https://github.com/basicai/xtreme1/files/9835773/lidar_fusion.zip)
压缩包已提供  上传之后会出现两个一摸一样的标注任务 且刷新之后还是2个
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/72067297/197114263-dc973673-df35-43b6-947a-d6feff43b505.png">

**Comment by jaggerwang** [comment]
![image](https://user-images.githubusercontent.com/1255011/197123907-b6ef64df-84bb-4cf2-bd27-bbaab7f52836.png)
@heyu3913  压缩包里面有个隐藏目录，里面有重复的数据，删除掉即可。后面我们会安排修复这个问题，忽略掉隐藏目录。

**Comment by heyu3913** [comment]
好的 十分感谢

**Comment by heyu3913** [comment]
不是你说的这个原因    我重新上传了一个没有隐藏文件夹的压缩包。还是会出现这个问题
[lidar_fusion.zip](https://github.com/basicai/xtreme1/files/9836505/lidar_fusion.zip)
![image](https://user-images.githubusercontent.com/72067297/197134569-9794ebd1-853c-4aab-9c5e-66ccdfe1b16d.png)

**Comment by heyu3913** [comment]
补充一下：上传多组图片+点云时不会出现这个问题  只有上传单组时会出现重复标注任务

**Comment by jaggerwang** [comment]
经过确认，确实有此问题，预计下周一可以修复。

**Comment by nicozhan** [comment]
感谢您的耐心！我们刚刚发布了新版本v0.5.2，修复了此问题。
请更新最新版本，再试一次。

**Comment by heyu3913** [comment]
后端yml文件 拉的还是0.5.1的镜像

**Comment by jaggerwang** [comment]
已经修复，请再试试。
