### ISSUE TITLE
Nvidia Tesla T4 has been configured. If the image is abnormal after enabling model services

### ISSUE THREAD

**Issue by chenghxy** [basicai/xtreme1#62]
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=7908671774239666506 skey=@crypt_3c123217_2db170f4583c8cd9bb592f0f5a6d3cab mmweb_appid=wx_webfilehelper](https://user-images.githubusercontent.com/43922236/203193648-8ca28f5d-bd15-482c-bf6c-12b136a5baea.jpg)

**Comment by nicozhan** [comment]
Please make sure that the Nvidia driver has been installed and configured properly.
Currently, the model can be only installed in Linux OS, and [Nvidia-docker](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html) must be installed properly as well.
